### ISSUE TITLE
Impelement HTTP compression

### ISSUE THREAD

**Issue by EpicStep** [memlimit/clickhouse-cli#3]
## Feature Request
Implement HTTP compression:
- [x] gzip
- [ ] br
- [ ] deflate
- [ ] xz
Some information about clickhouse compression: [link](https://clickhouse.com/docs/en/interfaces/http/#compression)

**Comment by gvencadze** [comment]
Closing this issue cause implementing other compressions not necessary for now.
Will reopen when start working on it.
